import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Alancito's contact page",
  description: "Generated by create next app",
};

function ContactPage() {
      return (
        <>
        <span className="text-7xl">Contact Page</span>
        </>
      )
    }
    export default ContactPage