import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Alancito's Pricing page",
  description: "Generated by create next app",
};

function PricingPage() {
      return (
        <>
        <span className="text-7xl">Pricing Page</span>
        </>
      )
    }
    export default PricingPage